<a href="https://colab.research.google.com/github/hemi-32/Data-Analytics-using-python-project/blob/main/day3_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([90,85,78,98])
print(marks)


[90 85 78 98]


In [ ]:
import numpy as np
students=np.array([
    [90,85],
    [78,92],
    [88,95]
])
print(students)

[[90 85]
 [78 92]
 [88 95]]


In [ ]:
import numpy as np
arr=np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
arr=np.ones((2,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
import numpy as np
arr=np.random.rand(3)
print(arr)

[0.08286374 0.02249766 0.34962174]


In [ ]:
import numpy as np
matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

print(a+b)
print(a*b)
print(np.sqrt(a))
print(np.sum(a))
print(np.mean(b))

[11 22 33 44]
[ 10  40  90 160]
[1.         1.41421356 1.73205081 2.        ]
10
25.0


# **index**,**slice**

In [ ]:
import numpy as np
marks=np.array([90,85,78,92])
print(marks[2])


78


In [ ]:
import numpy as np
marks=np.array([90,85,78,92,80])
print(marks[1:4])

[85 78 92]


# **TASK**

# **student score analysis**

In [ ]:
scores=[91,87,76,64,88,85]
total=sum(scores)
average=total/len(scores)
highest=max(scores)
lowest=min(scores)

print("stident scores:",scores)
print("total marks:",total)
print("average marks:",average)
print("highest mark:",highest)
print("lowest marks:",lowest)

stident scores: [91, 87, 76, 64, 88, 85]
total marks: 491
average marks: 81.83333333333333
highest mark: 91
lowest marks: 64


# **sales array calculations**

In [ ]:
sales=[23000,43000,87000,12000,54000]
total_sales=sum(sales)
average_sales=total_sales/len(sales)
highest_sales=max(sales)
lowest_sales=min(sales)

print("monthly sales:",sales)
print("total sales:",total_sales)
print("average sales:",average_sales)
print("highest sales:",highest_sales)
print("lowest sales:",lowest_sales)

monthly sales: [23000, 43000, 87000, 12000, 54000]
total sales: 219000
average sales: 43800.0
highest sales: 87000
lowest sales: 12000
