<a href="https://colab.research.google.com/github/hemi-32/Data-Analytics-using-python-project/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **reshape**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
new_arr=arr.reshape(2,4)
print(new_arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
new_arr=arr.reshape(2,4)
print(new_arr.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# **aggregation,stats and axis operations**

In [ ]:
import numpy as np
marks=np.array([69,43,86,57,90])
average=np.mean(marks)
print(average)

69.0


In [ ]:
marks=np.array([98,54,76,32])
med=np.median(marks)
print(med)

65.0


# **TASK**

# ANALYSIS PRODUCT SALES PERFORMANCE **

In [ ]:
import numpy as np
products =["Laptop","Mobile","Tablet","Headphone","Smartwatch"]

#Sales units
sales = np.array([120,250,80,150,100])

#Total sales
print("Total sales:",np.sum(sales))

#Avarage sales
print("Avarage sales:",np.mean(sales))

#Highest sales
print("Highest sales",np.max(sales))

#Lowest sales
print("Lowest sales",np.min(sales))

#Best-selling product
best_index =np.argmax(sales)
print("Best selling product:",products[best_index])

#Product-wise sales
print("\nProduct sales Report")
for i in range(len(products)):
 print(products[i],":",sales[i])


Total sales: 700
Avarage sales: 140.0
Highest sales 250
Lowest sales 80
Best selling product: Mobile

Product sales Report
Laptop : 120
Mobile : 250
Tablet : 80
Headphone : 150
Smartwatch : 100
